-- ============================================================================
-- 041 — Reihenfolgen (Kegelabend-Teilnehmer, Strafenkatalog) + Avatar-Upload
-- ----------------------------------------------------------------------------
-- (1) session_participants.seq
--     Die Teilnehmer lassen sich im Kegelabend per Drag & Drop sortieren. Die
--     Reihenfolge gilt den ganzen Abend (Spiele, Torschützen, Liste) und muss
--     darum ein Neuladen des Entwurfs überstehen. save_session fügt die
--     Teilnehmer in der Reihenfolge des übergebenen Arrays ein — eine
--     Identity-Spalte hält genau diese Reihenfolge fest, ohne dass die RPC
--     angefasst werden muss.
--
-- (2) penalties_catalog.sort_order + reorder_penalties()
--     Der Kassenwart legt die Reihenfolge des Katalogs per Drag & Drop fest;
--     der Kegelabend zeigt die Strafen dann genau so an. Bestehende Kataloge
--     behalten ihre bisherige (alphabetische) Reihenfolge.
--     Der Benachrichtigungs-Trigger „Strafenkatalog wurde geändert" feuert ab
--     jetzt nur noch bei inhaltlichen Änderungen — ein Umsortieren ist keine
--     Nachricht an den ganzen Club wert.
--
-- (3) Avatar-Upload: „new row violates row-level security policy"
--     Der Client lädt mit upsert: true hoch. Storage schreibt dafür per
--     INSERT … ON CONFLICT DO UPDATE … RETURNING — und das verlangt neben der
--     INSERT- und UPDATE- auch eine SELECT-Policy auf die betroffene Zeile.
--     Die gab es bewusst nicht (damit niemand den Bucket auflisten kann), also
--     schlug JEDER Upload fehl. Neu: SELECT nur auf den eigenen Ordner bzw. den
--     Club-Ordner für die, die ihn beschreiben dürfen — Auflisten fremder
--     Ordner bleibt gesperrt. Öffentliche Bild-URLs brauchen ohnehin keine
--     Policy (public bucket).
--     Zusätzlich prüfte die Club-Policy noch group_role() (nur die ranghöchste
--     Rolle, alte Rollenliste). Sie folgt jetzt der groups_update-Policy aus
--     Migration 040: wer die Club-Einstellungen ändern darf, darf auch das Bild.
-- ============================================================================

-- ── (1) Teilnehmer-Reihenfolge ──────────────────────────────────────────────
ALTER TABLE session_participants
  ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_session_participants_session_seq
  ON session_participants (session_id, seq);

-- ── (2) Katalog-Reihenfolge ─────────────────────────────────────────────────
DROP TRIGGER IF EXISTS trg_notif_catalog ON penalties_catalog;
CREATE TRIGGER trg_notif_catalog
  AFTER INSERT OR DELETE
     OR UPDATE OF name, amount, manual_amount, icon, active, charge_others, game_kind, stat_kind
  ON penalties_catalog
  FOR EACH ROW EXECUTE FUNCTION notif_on_catalog();

ALTER TABLE penalties_catalog
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;

-- Bisherige Anzeige war alphabetisch — genau so vorbelegen.
UPDATE penalties_catalog c
   SET sort_order = o.rn
  FROM (
    SELECT id, row_number() OVER (PARTITION BY group_id ORDER BY name, id) AS rn
    FROM penalties_catalog
  ) o
 WHERE o.id = c.id;

-- Neue Strafen landen am Ende des Katalogs, ohne dass der Client rechnen muss.
CREATE OR REPLACE FUNCTION public.trg_penalties_catalog_sort_order()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.sort_order IS NULL OR NEW.sort_order = 0 THEN
    SELECT COALESCE(MAX(sort_order), 0) + 1 INTO NEW.sort_order
      FROM penalties_catalog WHERE group_id = NEW.group_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_penalties_catalog_sort_order ON penalties_catalog;
CREATE TRIGGER trg_penalties_catalog_sort_order
  BEFORE INSERT ON penalties_catalog
  FOR EACH ROW EXECUTE FUNCTION trg_penalties_catalog_sort_order();

-- Reihenfolge setzen. SECURITY INVOKER: es gilt die penalties_update-Policy
-- (Kasse), genau wie beim Bearbeiten einer einzelnen Strafe.
CREATE OR REPLACE FUNCTION public.reorder_penalties(p_group_id UUID, p_ids UUID[])
RETURNS VOID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Nicht authentifiziert';
  END IF;
  IF NOT has_group_role(p_group_id, ARRAY['admin','kassenwart','kassenprüfer']) THEN
    RAISE EXCEPTION 'Keine Berechtigung';
  END IF;

  UPDATE penalties_catalog c
     SET sort_order = x.ord
    FROM unnest(p_ids) WITH ORDINALITY AS x(id, ord)
   WHERE c.id = x.id
     AND c.group_id = p_group_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.reorder_penalties(UUID, UUID[]) FROM anon, public;
GRANT  EXECUTE ON FUNCTION public.reorder_penalties(UUID, UUID[]) TO authenticated;

-- ── (3) Avatar-Storage ──────────────────────────────────────────────────────
-- Profilbild: eigener Ordner user/<uid>/
DROP POLICY IF EXISTS avatars_user_select ON storage.objects;
CREATE POLICY avatars_user_select ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'user'
    AND (storage.foldername(name))[2] = auth.uid()::text
  );

DROP POLICY IF EXISTS avatars_user_update ON storage.objects;
CREATE POLICY avatars_user_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'user'
    AND (storage.foldername(name))[2] = auth.uid()::text
  )
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'user'
    AND (storage.foldername(name))[2] = auth.uid()::text
  );

DROP POLICY IF EXISTS avatars_user_delete ON storage.objects;
CREATE POLICY avatars_user_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'user'
    AND (storage.foldername(name))[2] = auth.uid()::text
  );

-- Club-Bild: club/<groupId>/ — dieselben Rollen wie groups_update (Migration 040).
-- Die Gruppen-id wird erst nach der Ordnerprüfung gecastet, damit fremde
-- Pfade nicht mit einem Cast-Fehler statt einer sauberen Ablehnung enden.
CREATE OR REPLACE FUNCTION public.can_edit_club_avatar(p_folder TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
BEGIN
  IF p_folder IS NULL OR p_folder !~ '^[0-9a-fA-F-]{36}$' THEN
    RETURN FALSE;
  END IF;
  RETURN has_group_role(p_folder::uuid,
    ARRAY['admin','präsident','vizepräsident','kassenwart','kassenprüfer']);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.can_edit_club_avatar(TEXT) FROM anon, public;
GRANT  EXECUTE ON FUNCTION public.can_edit_club_avatar(TEXT) TO authenticated;

DROP POLICY IF EXISTS avatars_club_select ON storage.objects;
CREATE POLICY avatars_club_select ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'club'
    AND public.can_edit_club_avatar((storage.foldername(name))[2])
  );

DROP POLICY IF EXISTS avatars_club_write ON storage.objects;
CREATE POLICY avatars_club_write ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'club'
    AND public.can_edit_club_avatar((storage.foldername(name))[2])
  );

DROP POLICY IF EXISTS avatars_club_update ON storage.objects;
CREATE POLICY avatars_club_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'club'
    AND public.can_edit_club_avatar((storage.foldername(name))[2])
  )
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'club'
    AND public.can_edit_club_avatar((storage.foldername(name))[2])
  );

DROP POLICY IF EXISTS avatars_club_delete ON storage.objects;
CREATE POLICY avatars_club_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = 'club'
    AND public.can_edit_club_avatar((storage.foldername(name))[2])
  );
